// Generated by CoffeeScript 1.3.3
(function() {
  var R, acre_m2, draw_acre, draw_box, fg, geocoder, map, square_box, straight_line, to_deg, to_rad;

  R = 6378100;

  acre_m2 = 4046.86;

  window.side_of_acre = Math.sqrt(acre_m2);

  to_rad = function(deg) {
    return deg * Math.PI / 180;
  };

  to_deg = function(rad) {
    return rad * 180 / Math.PI;
  };

  draw_box = function(layer, corners) {
    return L.rectangle(corners).addTo(layer);
  };

  straight_line = function(starting_coords, distance, bearing) {
    var b, dist, lat1, lat2, lng1, lng2;
    b = to_rad(bearing);
    lat1 = to_rad(starting_coords.lat);
    lng1 = to_rad(starting_coords.lng);
    dist = distance / R;
    lat2 = Math.asin(Math.sin(lat1) * Math.cos(dist) + Math.cos(lat1) * Math.sin(dist) * Math.cos(b));
    lng2 = lng1 + Math.atan2(Math.sin(b) * Math.sin(dist) * Math.cos(lat1), Math.cos(dist) - Math.sin(lat1) * Math.sin(lat2));
    lng2 = (lng2 + 3 * Math.PI) % (2 * Math.PI) - Math.PI;
    return [starting_coords, L.latLng(to_deg(lat2), to_deg(lng2))];
  };

  square_box = function(center, side_length) {
    var half_diagonal, north_west, south_east;
    half_diagonal = Math.sqrt(2 * (side_length / 2) * (side_length / 2));
    north_west = straight_line(center, half_diagonal, 315)[1];
    south_east = straight_line(center, half_diagonal, 135)[1];
    return [north_west, south_east];
  };

  draw_acre = function(m, layer, side_of_acre) {
    layer.clearLayers();
    return draw_box(layer, square_box(m.getCenter(), side_of_acre));
  };

  geocoder = L.mapbox.geocoder('sklise.giaje9f5');

  map = L.mapbox.map('map', 'sklise.giaje9f5').setView([40.7280, -73.9453], 18);

  fg = L.featureGroup().addTo(map);

  draw_acre(map, fg, side_of_acre);

  map.on("move", function() {
    return draw_acre(map, fg, side_of_acre);
  });

  map.on("zoom", function() {
    return draw_acre(map, fg, side_of_acre);
  });

  map.on("resize", function() {
    return draw_acre(map, fg, side_of_acre);
  });

  map.on("viewreset", function() {
    return draw_acre(map, fg, side_of_acre);
  });

}).call(this);
